export const ProductService =
[
    {
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-1.jpeg",
        price: 200,
        priceDiscount: 100,
        hasOff: true,
    },
    {
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-5.jpeg",
        price: 300,
        priceDiscount: 100,
        hasOff: true,
    },
    {
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-3.jpeg",
        price: 500,
        priceDiscount: 300,
        hasOff: false,
    },
    {
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-4.jpeg",
        price: 400,
        priceDiscount: 350,
        hasOff: false,
    },
    {
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-5.jpeg",
        price: 300,
        priceDiscount: 100,
        hasOff: false,
    },
    {
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-2.jpeg",
        price: 300,
        priceDiscount: 100,
        hasOff: true,
    },
    {
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-3.jpeg",
        price: 300,
        priceDiscount: 100,
        hasOff: false,
    },
    {
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-1.jpeg",
        price: 300,
        priceDiscount: 100,
        hasOff: false,
    },
    {
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-4.jpeg",
        price: 300,
        priceDiscount: 100,
        hasOff: true,
    },
    {
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-3.jpeg",
        price: 300,
        priceDiscount: 100,
        hasOff: true,
    },
    {
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-1.jpeg",
        price: 300,
        priceDiscount: 100,
        hasOff: true,
    },{
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-3.jpeg",
        price: 300,
        priceDiscount: 100,
        hasOff: false,
    },{
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-5.jpeg",
        price: 300,
        priceDiscount: 100,
        hasOff: true,
    },
    {
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-1.jpeg",
        price: 300,
        priceDiscount: 100,
        hasOff: false,
    },{
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-3.jpeg",
        price: 300,
        priceDiscount: 100,
        hasOff: false,
    },{
        name: "K-Swiss V8 - Masculino",
        image: "/produc-image-2.jpeg",
        price: 300,
        priceDiscount: 100,
        hasOff: false,
    }
]
